apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: product
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /product(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: product-service
            port:
              number: 4005
